import { verify as verifyXEdDSA } from 'curve25519-js';

/**
 * Device-authorization signatures (Phase 2 T2, spec §3 + §12 Stage-0
 * amendment (d), NORMATIVE).
 *
 * Two constructions, each with an explicit ASCII context prefix whose first
 * byte ≠ 0x05, so neither can ever reinterpret as the other or as the FROZEN
 * §6.1 registration-lock layout (which starts with a 0x05-leading 33-byte
 * key and stays byte-exact as landed — the Matrix CVE-2022-39250 class is
 * exactly what these prefixes kill; falsification 25):
 *
 *   enrollment E = sig_IK ("fp-enroll-v1\0" ‖ utf8(userId) ‖ dakPub(33) ‖
 *                          utf8(createdAtMs))
 *   device list  = sig_DAK("fp-list-v1\0" ‖ listCanonical bytes)
 *
 * `createdAtMs` is the integer milliseconds-since-epoch the client signed —
 * its decimal UTF-8 form goes under the signature, matching the §6.1
 * precedent of binding integers as their decimal representation.
 *
 * The signing side is the Signal XEdDSA construction
 * (`Curve.calculateSignature` in libsignal_protocol_dart, mirrored in
 * frontend/lib/services/device_list/device_authority_engine.dart);
 * `curve25519-js.verify` implements the matching convention over the 32-byte
 * Montgomery key WITHOUT the 0x05 type byte. Real-client vectors are pinned
 * in device-list-signature.util.spec.ts (generated by
 * frontend/tool/device_list_vector_generator.dart) so a dependency swap or an
 * encoding drift fails loudly.
 *
 * Fails CLOSED: malformed input, wrong length, or a thrown error is a
 * rejection, never an acceptance.
 */

export const ENROLL_CONTEXT = 'fp-enroll-v1\0';
export const LIST_CONTEXT = 'fp-list-v1\0';
/** Reserved for T3/T6 (§6.3 rotation). Declared so all three domains live
 * together; the rotation construction itself is deliberately NOT built in
 * T2. */
export const DAK_ROTATE_CONTEXT = 'fp-dak-rotate-v1\0';

export const SERIALIZED_PUBLIC_KEY_LENGTH = 33;
export const SIGNATURE_LENGTH = 64;

/** Curve25519 public keys are serialized with this leading type byte. */
const DJB_TYPE_BYTE = 0x05;

function decodeExact(value: string, expectedLength: number): Buffer | null {
  if (typeof value !== 'string' || value.length === 0) return null;
  let decoded: Buffer;
  try {
    decoded = Buffer.from(value, 'base64');
  } catch {
    return null;
  }
  // Buffer.from silently ignores invalid base64; the length check is the real
  // validation, and the signature check makes a forgery attempt useless.
  if (decoded.length !== expectedLength) return null;
  return decoded;
}

/** Exact bytes the identity key signs for the enrollment record E. */
export function buildEnrollmentMessage(
  userId: number,
  dakPub: Buffer,
  createdAtMs: number,
): Buffer {
  return Buffer.concat([
    Buffer.from(ENROLL_CONTEXT, 'utf8'),
    Buffer.from(String(userId), 'utf8'),
    dakPub,
    Buffer.from(String(createdAtMs), 'utf8'),
  ]);
}

/** Exact bytes the DAK signs for the device list. */
export function buildDeviceListMessage(canonical: Buffer): Buffer {
  return Buffer.concat([Buffer.from(LIST_CONTEXT, 'utf8'), canonical]);
}

function verify(
  signerPubSerialized: Buffer,
  message: Buffer,
  signature: Buffer,
): boolean {
  if (signerPubSerialized[0] !== DJB_TYPE_BYTE) return false;
  // The verifier strips the sign bit from the key and the signature IN PLACE
  // (same curve25519-js caveat the §6.1 verifier documents) — fresh
  // Uint8Arrays keep that mutation off any caller-owned buffer.
  const verifyKey = Uint8Array.from(signerPubSerialized.subarray(1));
  const verifyMessage = Uint8Array.from(message);
  const verifySignature = Uint8Array.from(signature);
  try {
    return verifyXEdDSA(verifyKey, verifyMessage, verifySignature) === true;
  } catch {
    return false;
  }
}

export interface EnrollmentProofInput {
  /** base64, 33 bytes — the identity key the account currently publishes. */
  identityPublicKey: string;
  userId: number;
  /** base64, 33 bytes — the DAK public key being enrolled. */
  dakPub: string;
  /** Integer milliseconds since epoch, exactly as signed. */
  createdAtMs: number;
  /** base64, 64 bytes — XEdDSA signature by the identity key. */
  signature: string;
}

/** Verifies enrollment record E (chain link IK → E → DAK, invariant I7). */
export function verifyEnrollmentSignature(
  input: EnrollmentProofInput,
): boolean {
  const identityKey = decodeExact(
    input.identityPublicKey,
    SERIALIZED_PUBLIC_KEY_LENGTH,
  );
  const dakPub = decodeExact(input.dakPub, SERIALIZED_PUBLIC_KEY_LENGTH);
  const signature = decodeExact(input.signature, SIGNATURE_LENGTH);
  if (!identityKey || !dakPub || !signature) return false;
  if (dakPub[0] !== DJB_TYPE_BYTE) return false;
  if (!Number.isInteger(input.userId) || input.userId <= 0) return false;
  if (!Number.isInteger(input.createdAtMs) || input.createdAtMs <= 0) {
    return false;
  }
  return verify(
    identityKey,
    buildEnrollmentMessage(input.userId, dakPub, input.createdAtMs),
    signature,
  );
}

export interface DeviceListProofInput {
  /** base64, 33 bytes — the enrolled DAK public key. */
  dakPub: string;
  /** The received canonical bytes VERBATIM (falsification 23). */
  canonical: Buffer;
  /** base64, 64 bytes — XEdDSA signature by the DAK. */
  signature: string;
}

/** Verifies the device-list signature (chain link DAK → list). */
export function verifyDeviceListSignature(
  input: DeviceListProofInput,
): boolean {
  const dakPub = decodeExact(input.dakPub, SERIALIZED_PUBLIC_KEY_LENGTH);
  const signature = decodeExact(input.signature, SIGNATURE_LENGTH);
  if (!dakPub || !signature) return false;
  return verify(dakPub, buildDeviceListMessage(input.canonical), signature);
}
