/**
 * Cross-language regression vectors, generated by the REAL Flutter client
 * (libsignal_protocol_dart 0.8.2 `Curve.calculateSignature` — generator:
 * frontend/tool/device_list_vector_generator.dart, recorded run 2026-08-20):
 * one identity key signing enrollment E over a freshly minted DAK, that DAK
 * signing the canonical v1 and v2 lists, and the SAME identity key producing
 * a frozen §6.1 registration-lock signature.
 *
 * Load-bearing twice over: (1) the server must accept exactly what the client
 * produces — a dependency swap or an encoding drift fails the pinned specs
 * instead of silently refusing every legitimate enrollment; (2) falsification
 * 25 — a signature minted for any ONE construction is rejected by every OTHER
 * construction's verifier (§12 Stage-0 amendment (d), the CVE-2022-39250
 * class).
 *
 * Its own module (not inside a spec) because two spec files share it —
 * importing one spec from another would re-register the imported file's
 * describe blocks and double-run them.
 */
export const DEVICE_LIST_VECTOR = {
  userId: 4242,
  createdAtMs: 1755600000000,
  identityPublicKey: 'BVw09InzjViJv0A1XIG8C/4r2n6MWn6R/ng/BmNas0Rz',
  dakPub: 'BRMYysMt4d8jNJ5RKYTUG6PUOj58btxSGEZ/uqtIiGQB',
  enrollmentSig:
    'kHzHV03U8ncufufHlyTCAm+XTyY8MRyUSx4raQINTokfMTw6oNoj3SUTp4kg1j7tUnQENOTOPcvgDTWSNAqfBQ==',
  listCanonical:
    'eyJ1c2VySWQiOjQyNDIsInZlcnNpb24iOjEsImRldmljZXMiOlt7ImFkZGVkQXQiOjE3NTU2MDAwMDAwMDAsImRldmljZUlkIjoxLCJwbGF0Zm9ybSI6ImFuZHJvaWQifV19',
  listSignature:
    'BZ+voGZnRR3gms8JbuxGqEozLhLOPfD0ZsMZmDEPbaY/cQhSX/2DH/efVptNku7ujw+9o2S3JQWKIArsFhUviA==',
  v2ListCanonical:
    'eyJ1c2VySWQiOjQyNDIsInZlcnNpb24iOjIsImRldmljZXMiOlt7ImFkZGVkQXQiOjE3NTU2MDAwMDAwMDAsImRldmljZUlkIjoxLCJuYW1lIjoicHJpbWFyeSIsInBsYXRmb3JtIjoiYW5kcm9pZCJ9XX0=',
  v2ListSignature:
    '2/3Bt9JLlzOo28/LtwtPnO1bcNTdh27gN+pjUVoLxfTtOnmYYlor4iaIGN6hhgS5TlBsfPtx83XSLREceVYHhQ==',
  lockNewIdentityPublicKey: 'BUmkuSUvi0GgVgLsOj+YJJ85lVlQ5xx2gAidYUp5cVBh',
  lockNonce: 'AAcOFRwjKjE4P0ZNVFtiaXB3foWMk5qhqK+2vcTL0tk=',
  lockSignature:
    'ZawQAcB9Ee8YCxzYMcejEWIPEA9c2fImQ2TH4YemAtXKY9bzCKcgWeutcd+UgSm5crKg/ZJtVVZRg9nEbnOeAg==',
};
