import {
  buildIdentityChangeMessage,
  IdentityChangeProofInput,
  verifyIdentityChangeSignature,
} from './identity-signature.util';

/**
 * Cross-language regression vector, generated by the REAL Flutter client
 * (libsignal_protocol_dart 0.8.2, `Curve.calculateSignature`): an old identity
 * key pair signing over a new identity key's serialized bytes, the account id,
 * and a 32-byte nonce.
 *
 * This is the load-bearing compatibility claim of the registration lock — the
 * server must accept exactly what the client produces. If a dependency swap or
 * an encoding change ever breaks that, this vector fails instead of the lock
 * silently refusing every legitimate replacement (or, far worse, accepting
 * signatures the client never made).
 */
const VECTOR = {
  oldIdentityPublicKey: 'BdYgkTwp7ZAWQHWKYxQtsMQZxtVQEtVs1Fo63JM3EKJQ',
  newIdentityPublicKey: 'BV/AuiEQx2o3p6cfoebDWHomEc5VTzNsyNNcuYxf3BVF',
  nonce: 'AwoRGB8mLTQ7QklQV15lbHN6gYiPlp2kq7K5wMfO1dw=',
  signature:
    '+eSga6vQusMMR5gjRe2rk/XQspEwDVXBmFmGy/1iH2P8kBGS+xQ+vE+xTbnzF+3m878LvYXbIooBi4sAmes7hA==',
  userId: 4242,
};

const validInput = () => ({
  storedIdentityPublicKey: VECTOR.oldIdentityPublicKey,
  newIdentityPublicKey: VECTOR.newIdentityPublicKey,
  userId: VECTOR.userId,
  nonce: VECTOR.nonce,
  signature: VECTOR.signature,
});

describe('verifyIdentityChangeSignature (registration lock §6.1)', () => {
  it('accepts a signature produced by the real Flutter client', () => {
    expect(verifyIdentityChangeSignature(validInput())).toBe(true);
  });

  it('rejects the signature when a DIFFERENT new identity key is claimed', () => {
    // The signature commits to the new key, so swapping it must invalidate the
    // proof — otherwise a captured signature would authorize any replacement.
    expect(
      verifyIdentityChangeSignature({
        ...validInput(),
        newIdentityPublicKey: VECTOR.oldIdentityPublicKey,
      }),
    ).toBe(false);
  });

  it('rejects the signature when replayed for a different account', () => {
    expect(
      verifyIdentityChangeSignature({ ...validInput(), userId: 4243 }),
    ).toBe(false);
  });

  it('rejects the signature when replayed with a different nonce', () => {
    const otherNonce = Buffer.alloc(32, 9).toString('base64');
    expect(
      verifyIdentityChangeSignature({ ...validInput(), nonce: otherNonce }),
    ).toBe(false);
  });

  it('rejects a signature verified against a different stored identity key', () => {
    expect(
      verifyIdentityChangeSignature({
        ...validInput(),
        storedIdentityPublicKey: VECTOR.newIdentityPublicKey,
      }),
    ).toBe(false);
  });

  it('rejects a tampered signature', () => {
    const tampered = Buffer.from(VECTOR.signature, 'base64');
    tampered[5] ^= 1;
    expect(
      verifyIdentityChangeSignature({
        ...validInput(),
        signature: tampered.toString('base64'),
      }),
    ).toBe(false);
  });

  it('does not mutate the caller-supplied buffers', () => {
    // The underlying verifier clears sign bits in place; a leaked mutation
    // would corrupt the stored key or the signature for any later use.
    const input = validInput();
    const before = { ...input };
    verifyIdentityChangeSignature(input);
    expect(input).toEqual(before);
  });

  const failureCases: Array<[string, Partial<IdentityChangeProofInput>]> = [
    ['empty signature', { signature: '' }],
    ['empty nonce', { nonce: '' }],
    ['short signature', { signature: Buffer.alloc(63).toString('base64') }],
    ['long signature', { signature: Buffer.alloc(65).toString('base64') }],
    ['short nonce', { nonce: Buffer.alloc(31).toString('base64') }],
    ['non-base64 signature', { signature: '!!!not-base64!!!' }],
    [
      'stored key without the 0x05 type byte',
      { storedIdentityPublicKey: Buffer.alloc(33, 4).toString('base64') },
    ],
    [
      'stored key of the wrong length',
      { storedIdentityPublicKey: Buffer.alloc(32, 5).toString('base64') },
    ],
    ['zero userId', { userId: 0 }],
    ['negative userId', { userId: -1 }],
    ['non-integer userId', { userId: 1.5 }],
  ];

  it.each(failureCases)('fails closed on %s', (_label, override) => {
    expect(
      verifyIdentityChangeSignature({ ...validInput(), ...override }),
    ).toBe(false);
  });
});

describe('buildIdentityChangeMessage', () => {
  it('concatenates new key, decimal account id, and nonce in that order', () => {
    const newKey = Buffer.from(VECTOR.newIdentityPublicKey, 'base64');
    const nonce = Buffer.from(VECTOR.nonce, 'base64');
    const message = buildIdentityChangeMessage(newKey, VECTOR.userId, nonce);

    expect(message.length).toBe(33 + String(VECTOR.userId).length + 32);
    expect(message.subarray(0, 33).equals(newKey)).toBe(true);
    expect(message.subarray(33, 37).toString('utf8')).toBe('4242');
    expect(message.subarray(37).equals(nonce)).toBe(true);
  });
});
